import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const cjsStub = require("./vitest-expect.cjs");

export default cjsStub.default;
export const expect = cjsStub.expect;
export const MATCHERS_OBJECT = cjsStub.MATCHERS_OBJECT;
export const JEST_MATCHERS_OBJECT = cjsStub.JEST_MATCHERS_OBJECT;
export const GLOBAL_EXPECT = cjsStub.GLOBAL_EXPECT;
export const ASYMMETRIC_MATCHERS_OBJECT = cjsStub.ASYMMETRIC_MATCHERS_OBJECT;
export const spies = cjsStub.spies;
export const getState = cjsStub.getState;
export const setState = cjsStub.setState;
export const Any = cjsStub.Any;
export const Anything = cjsStub.Anything;
export const ArrayContaining = cjsStub.ArrayContaining;
export const AsymmetricMatcher = cjsStub.AsymmetricMatcher;
export const ObjectContaining = cjsStub.ObjectContaining;
export const StringContaining = cjsStub.StringContaining;
export const StringMatching = cjsStub.StringMatching;
export const arrayBufferEquality = cjsStub.arrayBufferEquality;
export const sparseArrayEquality = cjsStub.sparseArrayEquality;
export const subsetEquality = cjsStub.subsetEquality;
export const equals = cjsStub.equals;
export const iterableEquality = cjsStub.iterableEquality;
export const typeEquality = cjsStub.typeEquality;
export const isAsymmetric = cjsStub.isAsymmetric;
export const hasAsymmetric = cjsStub.hasAsymmetric;
export const isImmutableUnorderedKeyed = cjsStub.isImmutableUnorderedKeyed;
export const isImmutableUnorderedSet = cjsStub.isImmutableUnorderedSet;
export const isA = cjsStub.isA;
export const hasProperty = cjsStub.hasProperty;
export const getObjectKeys = cjsStub.getObjectKeys;
export const getObjectSubset = cjsStub.getObjectSubset;
export const generateToBeMessage = cjsStub.generateToBeMessage;
export const fnNameFor = cjsStub.fnNameFor;
export const pluralize = cjsStub.pluralize;
export const addCustomEqualityTesters = cjsStub.addCustomEqualityTesters;
export const JestAsymmetricMatchers = cjsStub.JestAsymmetricMatchers;
export const JestChaiExpect = cjsStub.JestChaiExpect;
export const JestExtend = cjsStub.JestExtend;
