name: Code Quality CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  quality:
    name: Code Quality and Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      
      - name: Install dependencies
        run: |
          uv sync --frozen
      
      - name: Run Black formatting check
        run: |
          uv run black --check --diff src/ tests/ scripts/
      
      - name: Run Mypy type checking
        run: |
          uv run mypy src scripts tests
      
      - name: Run architecture validation
        run: |
          if [ -f scripts/check_architecture.py ]; then
            uv run python scripts/check_architecture.py
          else
            echo "Architecture validation script not found, skipping..."
          fi
      
      - name: Run test suite
        run: |
          uv run pytest tests/ -v --tb=short --cov=src --cov-report=term-missing --cov-report=xml
      
      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml